### ISSUE TITLE
EXCEPTION: this.appInsights.downloadAndSetup is not a function

### ISSUE THREAD

**Issue by ntclark4** [harry671003/ng2-appinsights#3] opened 2017-02-23 21:38 UTC
I'm using the latest version of this package with Angular 2.2.4. Running with webpack and ASP.NET Core as seen [here](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/).

I don't have any trouble until I run the project and get the following error: 

> TypeError: this.appInsights.downloadAndSetup is not a function

and

> Unhandled Promise rejection: this.appInsights.downloadAndSetup is not a function ; Zone: < root > ; Task: Promise.then ; Value: TypeError: this.appInsights.downloadAndSetup is not a function

![image](https://cloud.githubusercontent.com/assets/25378305/23280218/fb4daee8-f9dd-11e6-9f6e-6ec7718607b1.png)

**Comment by harry671003** [comment] 2017-03-08 03:33
Are you explicitly adding another app insights js script to your page?

**Comment by ntclark4** [comment] 2017-03-08 15:24
No. I'm following the the instructions exactly. I have ng2-appinsights configured and nothing else.

**Comment by harry671003** [comment] 2017-03-10 06:46
@ntclark4 Can you check if the issue is fixed in v 0.5.0?

**Comment by ntclark4** [comment] 2017-03-14 18:18
Thanks for looking at this @harry671003 

After updating the package and setting up app insights again, I get the exact same error.

I thought I'd test it in with an Angular CLI project, and it worked without any errors. So, I'm wondering if there's a conflict with something in webpack.

**Comment by steven-r** [comment] 2017-03-19 22:39
I'd the same problem recently... 

Do you have the standard appInsights declaration (the one that is injected by the app-insights setup procedure inside VS) still in place (look at index.html)? Removing this snipped did the trick for me...

**Comment by harry671003** [comment] 2017-03-27 03:38
Closing this assuming that the issue is fixed now.

**Closed as completed by harry671003** 2017-03-27 03:38 UTC

**Comment by rbamadeus** [comment] 2017-05-12 20:59
I just downloaded ng2-appinsights and I'm getting this issue.  When I put a break point in the init, sure enough it says the downloadAndSetup is undefined. We are not using webpack, if that matters. Any thoughts of where I should look to figure out if I have something setup incorrectly or what might be missing?

**Comment by ntclark4** [comment] 2017-05-16 14:16
I have not taken a look at this the past month since this is not a priority in the project. If you run across a solution, please share it here, and I will do the same.

**Comment by tabareh** [comment] 2017-10-05 12:19
No update on this? We have the same problem

**Comment by tabareh** [comment] 2017-10-05 13:43
We found the issue in our case. The initialization of appInsights object should be done using either AppInsightService.Init or using the Microsoft script
```javascript
<script type="text/javascript">
    var appInsights = blahblahblah
    }({
      instrumentationKey: "xxxx"
    });

    window.appInsights = appInsights;
    appInsights.trackPageView();

  </script>
```
Don't mix both together. If you want to use the script in page, then comment out the line in appInsightService
```
this.appInsights.downloadAndSetup(config);
```
